version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb
      - redis
  frontend:
    build:
      context: ./frontend
    ports:
      - 80:80
    depends_on:
      - backend
  mongodb:
    image: public.ecr.aws/docker/library/mongo:latest
    ports:
      - 27017:27017
  redis:
    image: public.ecr.aws/ubuntu/redis:latest
    ports:
      - 6379:6379
