version: "3"
services:
  backend:
    build:
      context: ./backend
    ports:
      - 3000:3000
    depends_on:
      - mongodb
      - redis
  frontend:
    build:
      context: ./frontend
    ports:
      - 80:80
    depends_on:
      - backend
  mongodb:
    image: mongo
    ports:
      - 27017:27017
  redis:
    image: redis
    ports:
      - 6379:6379
